### ISSUE TITLE
this probably isnt your fault, but i have a too many open files error when applying any theme

### ISSUE THREAD

**Issue by MacncheeseTTR** [lr-tech/rofi-themes-collection#10]

**Comment by newmanls** [comment]
Hi! Could you provide more information?

**Comment by MacncheeseTTR** [comment]
it seems to only be on the nord theme, it gives an error mentioning an other completely different theme

**Comment by newmanls** [comment]
Please, send the output of this command `rofi -dump-config -dump-theme`
