### ISSUE TITLE
[Rounded themes] When there are less than 8 results (maximum shown) the whole window gets squished and unreadable. 

### ISSUE THREAD

**Issue by DeaDvey** [lr-tech/rofi-themes-collection#11]
[Hyprland] When there are less than 8 results available on the rouded theme (Nord) the whole window becomes squished and the text and images become unreadable, though it is relative to how many results there are. This visual bug only lasts around a second before resising properly.
![image](https://github.com/newmanls/rofi-themes-collection/assets/104674266/08945e95-e158-4caa-b3b7-e01a13434502)

![image](https://github.com/newmanls/rofi-themes-collection/assets/104674266/b75d7aec-74e5-4fff-8e89-167b9a8f4e3a)

**Comment by DeaDvey** [comment]
I found a potential solution, however the window will not auto resize, I'll open a PR so you can see.
If you add a "height: 390px;" to the window in rounded-common it will not have the visual bug anymore, but again, auto resizing will not happen.

**Comment by newmanls** [comment]
Apparently I don't have that issue. Have you checked if its rather related to your compositor?

**Comment by DeaDvey** [comment]
Hmm, maybe, are you using sway?

**Comment by newmanls** [comment]
I've tried with dwm (with picom and with no compositor) and xfce and it seems to work fine. If you're on wayland maybe you could try [this fork](https://github.com/lbonn/rofi) instead.

**Comment by DeaDvey** [comment]
Ah, thanks, this might fix the issue.

**Comment by newmanls** [comment]
No problem. Please let me know if it worked
