### ISSUE TITLE
theme selection problem

### ISSUE THREAD

**Issue by nemo231987** [lr-tech/rofi-themes-collection#19]
on my gentoo (openrc, wayland) I installed rofi, then installing the themes, I didn't receive any errors but when I select the theme I would like to set I receive this:

The following errors were detected when starting rofi:
Failed to open theme: /home/nemo/. local/share/rofi/ themes/rounded - common. rasi
Error: File o directory non esistente

I have this warning with any theme

**Comment by xXAnoHitoXx** [comment]
all of the rounded themes requires the rounded-common.rasi. you will have to add both the rounded-common.rasi and for example rounded-nord-dark.rasi

**Comment by newmanls** [comment]
It seems like the route you're sharing has some unexpected spaces. Could you share the your rofi config file? It should be at `~/.config/rofi/config.rasi` by default
