### ISSUE TITLE
Search icon not showing in spotlight theme

### ISSUE THREAD

**Issue by barkawa** [lr-tech/rofi-themes-collection#3]
The search icon (magnifying glass) isn't showing when using the spotlight-dark theme.

**Comment by regexPattern** [comment]
I have the same issue here. At first I thought I was missing a file named "search" but couldn't find it in the repo.

**Comment by newmanls** [comment]
Hi and sorry for the late answer!
It indeed uses a file named "search", but from your current icon theme. This way these rofi themes will match with your icon theme.
Make sure your icon theme have such file and, if not, you can make a copy of an existing magnifying glass icon (or something similar) from your icon theme and then rename it as "search"
