### ISSUE TITLE
Rounded nord dark is not vertically centered

### ISSUE THREAD

**Issue by RiccardoBarbieri** [lr-tech/rofi-themes-collection#5]
When using rounded-nord-dark.rasi theme, the window is not vertically centered as shown in the attached screenshot
![temp_screenshot](https://user-images.githubusercontent.com/43068188/206511695-fa9d31e2-148a-4c76-94db-039354b8e85f.png)

The output of `rofi -dump-theme` is

`/**
 * rofi -dump-theme output.
 * Rofi version: 1.7.1
 **/
* {
    text-color:       var(fg0);
    fg3:              rgba ( 76, 86, 106, 100 % );
    fg2:              rgba ( 216, 222, 233, 100 % );
    bg3:              rgba ( 136, 192, 208, 95 % );
    bg2:              rgba ( 76, 86, 106, 50 % );
    fg1:              rgba ( 236, 239, 244, 100 % );
    fg0:              rgba ( 216, 222, 233, 100 % );
    bg1:              rgba ( 59, 66, 82, 100 % );
    bg0:              rgba ( 46, 52, 64, 95 % );
    font:             "Roboto 12";
    background-color: transparent;
    spacing:          0px ;
    padding:          0px ;
    margin:           0px ;
}
window {
    width:            480;
    background-color: var(bg0);
    location:         center;
    border-radius:    24px ;
}
mainbox {
    padding: 12px ;
}
inputbar {
    padding:          8px 16px ;
    background-color: var(bg1);
    border:           2px ;
    border-color:     var(bg3);
    spacing:          8px ;
    border-radius:    16px ;
    children:         [ prompt,entry ];
}
prompt {
    text-color: var(fg2);
}
entry {
    placeholder:       "Search";
    placeholder-color: var(fg3);
}
message {
    margin:           12px 0px 0px ;
    background-color: var(bg2);
    border-color:     var(bg2);
    border-radius:    16px ;
}
textbox {
    padding: 8px 24px ;
}
listview {
    background-color: transparent;
    margin:           12px 0px 0px ;
    columns:          1;
    lines:            8;
    fixed-height:     false;
}
element {
    padding:       8px 16px ;
    spacing:       8px ;
    border-radius: 16px ;
}
element normal.active {
    text-color: var(bg3);
}
element selected {
    text-color: var(bg1);
}
element selected.normal {
    background-color: var(bg3);
}
element selected.active {
    background-color: var(bg3);
}
element-icon {
    size:           1em ;
    vertical-align: 0.50;
}
element-text {
    text-color: inherit;
}
`

**Comment by newmanls** [comment]
Hi!  As you can see in [this issue](https://github.com/newmanls/rofi-themes-collection/issues/4), Rofi changed its way to center windows since version 1.7.4, so you'll need to update Rofi so that theme displays correctly.
