### ISSUE TITLE
Rofi window is not in center.

### ISSUE THREAD

**Issue by tonmoy998** [lr-tech/rofi-themes-collection#9]
I am using spotlight and rounded but it always appears in the bottom-center.

**Comment by newmanls** [comment]
Hi! What rofi version are you running?

**Comment by tonmoy998** [comment]
Sorry for late reply!I did't have my computer.It's  1.7.3 on ubunu LTS 22.10

**Comment by newmanls** [comment]
For the themes to work correctly, you'll need at least rofi 1.7.4.
